/* Generated by scripts/extract-companion-data.py — do not edit by hand. */
window.COMPANION_DATA = {
  "catalog": {
    "project": "中国人群脚型数据可视化",
    "kind": "personal teaching samples from the 2020 GitHub Pages dashboard",
    "not_clinical": true,
    "sources": {
      "dashboard": "js/index.js",
      "unmounted_pressure_sketch": "draw1.js",
      "unmounted_thickness_sketch": "draw2.js"
    },
    "series": {
      "height_shoe": {
        "n_female": 199,
        "n_male": 199,
        "units": {
          "height": "cm",
          "shoe_length_label": "cm as plotted"
        }
      },
      "age_foot_length": {
        "ages": [
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14
        ],
        "units": "cm"
      },
      "bmi_shape": {
        "bmi": [
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24
        ],
        "note": "y is labeled 脚长/脚宽 but plotted as a 20–30 index"
      },
      "symmetry": {
        "ages": [
          2,
          3,
          4,
          5,
          6,
          7,
          8,
          9,
          10,
          11,
          12,
          13,
          14
        ],
        "note": "counts come from Math.log in the pie IIFE, not from raw pairs"
      },
      "radar": {
        "ages": [
          9,
          10,
          11,
          12
        ],
        "axes": [
          "身高",
          "兜跟围长",
          "跗骨围长",
          "跖趾围长",
          "鞋码",
          "脚长",
          "体重"
        ],
        "scale": "display scores 0–100, not raw centimetres"
      }
    }
  },
  "heightShoe": {
    "female": [
      {
        "height_cm": 121.83,
        "shoe_cm": 15.6
      },
      {
        "height_cm": 110.31,
        "shoe_cm": 17.52
      },
      {
        "height_cm": 116.04,
        "shoe_cm": 18.64
      },
      {
        "height_cm": 140.37,
        "shoe_cm": 19.21
      },
      {
        "height_cm": 118.99,
        "shoe_cm": 19.32
      },
      {
        "height_cm": 114.59,
        "shoe_cm": 18.59
      },
      {
        "height_cm": 114.01,
        "shoe_cm": 17.61
      },
      {
        "height_cm": 106.25,
        "shoe_cm": 13.95
      },
      {
        "height_cm": 100.26,
        "shoe_cm": 15.65
      },
      {
        "height_cm": 98.43,
        "shoe_cm": 13.62
      },
      {
        "height_cm": 139.36,
        "shoe_cm": 19.3
      },
      {
        "height_cm": 106.45,
        "shoe_cm": 14.7
      },
      {
        "height_cm": 102.39,
        "shoe_cm": 15.35
      },
      {
        "height_cm": 84.77,
        "shoe_cm": 13.03
      },
      {
        "height_cm": 95.58,
        "shoe_cm": 13.01
      },
      {
        "height_cm": 88.07,
        "shoe_cm": 11.95
      },
      {
        "height_cm": 95.45,
        "shoe_cm": 12.47
      },
      {
        "height_cm": 100.13,
        "shoe_cm": 15.54
      },
      {
        "height_cm": 117.45,
        "shoe_cm": 14.93
      },
      {
        "height_cm": 106.04,
        "shoe_cm": 15.12
      },
      {
        "height_cm": 102.95,
        "shoe_cm": 13.69
      },
      {
        "height_cm": 127.39,
        "shoe_cm": 17.88
      },
      {
        "height_cm": 109.95,
        "shoe_cm": 16.49
      },
      {
        "height_cm": 114.86,
        "shoe_cm": 14.64
      },
      {
        "height_cm": 145.0,
        "shoe_cm": 23.61
      },
      {
        "height_cm": 96.13,
        "shoe_cm": 15.25
      },
      {
        "height_cm": 124.65,
        "shoe_cm": 17.39
      },
      {
        "height_cm": 137.65,
        "shoe_cm": 21.13
      },
      {
        "height_cm": 151.98,
        "shoe_cm": 21.21
      },
      {
        "height_cm": 109.25,
        "shoe_cm": 14.04
      },
      {
        "height_cm": 147.53,
        "shoe_cm": 20.98
      },
      {
        "height_cm": 117.8,
        "shoe_cm": 17.26
      },
      {
        "height_cm": 80.96,
        "shoe_cm": 12.27
      },
      {
        "height_cm": 112.9,
        "shoe_cm": 16.12
      },
      {
        "height_cm": 115.54,
        "shoe_cm": 17.16
      },
      {
        "height_cm": 138.28,
        "shoe_cm": 18.75
      },
      {
        "height_cm": 147.1,
        "shoe_cm": 18.89
      },
      {
        "height_cm": 117.64,
        "shoe_cm": 18.63
      },
      {
        "height_cm": 145.03,
        "shoe_cm": 20.62
      },
      {
        "height_cm": 113.47,
        "shoe_cm": 16.68
      },
      {
        "height_cm": 101.51,
        "shoe_cm": 16.8
      },
      {
        "height_cm": 87.18,
        "shoe_cm": 13.34
      },
      {
        "height_cm": 140.39,
        "shoe_cm": 19.65
      },
      {
        "height_cm": 101.67,
        "shoe_cm": 14.48
      },
      {
        "height_cm": 123.86,
        "shoe_cm": 16.93
      },
      {
        "height_cm": 150.65,
        "shoe_cm": 18.92
      },
      {
        "height_cm": 92.46,
        "shoe_cm": 11.57
      },
      {
        "height_cm": 86.73,
        "shoe_cm": 14.03
      },
      {
        "height_cm": 130.94,
        "shoe_cm": 16.52
      },
      {
        "height_cm": 141.99,
        "shoe_cm": 17.85
      },
      {
        "height_cm": 148.18,
        "shoe_cm": 18.53
      },
      {
        "height_cm": 80.4,
        "shoe_cm": 11.67
      },
      {
        "height_cm": 85.32,
        "shoe_cm": 13.95
      },
      {
        "height_cm": 101.39,
        "shoe_cm": 14.82
      },
      {
        "height_cm": 152.64,
        "shoe_cm": 22.02
      },
      {
        "height_cm": 125.34,
        "shoe_cm": 19.75
      },
      {
        "height_cm": 102.11,
        "shoe_cm": 15.19
      },
      {
        "height_cm": 109.21,
        "shoe_cm": 18.05
      },
      {
        "height_cm": 107.27,
        "shoe_cm": 16.67
      },
      {
        "height_cm": 100.17,
        "shoe_cm": 13.25
      },
      {
        "height_cm": 124.44,
        "shoe_cm": 17.04
      },
      {
        "height_cm": 100.85,
        "shoe_cm": 13.94
      },
      {
        "height_cm": 132.84,
        "shoe_cm": 18.25
      },
      {
        "height_cm": 119.71,
        "shoe_cm": 19.52
      },
      {
        "height_cm": 88.69,
        "shoe_cm": 11.86
      },
      {
        "height_cm": 129.51,
        "shoe_cm": 16.75
      },
      {
        "height_cm": 126.13,
        "shoe_cm": 18.19
      },
      {
        "height_cm": 102.79,
        "shoe_cm": 15.95
      },
      {
        "height_cm": 125.96,
        "shoe_cm": 17.84
      },
      {
        "height_cm": 110.84,
        "shoe_cm": 15.8
      },
      {
        "height_cm": 80.96,
        "shoe_cm": 10.34
      },
      {
        "height_cm": 96.89,
        "shoe_cm": 13.15
      },
      {
        "height_cm": 93.14,
        "shoe_cm": 13.08
      },
      {
        "height_cm": 107.71,
        "shoe_cm": 15.34
      },
      {
        "height_cm": 86.17,
        "shoe_cm": 12.1
      },
      {
        "height_cm": 91.68,
        "shoe_cm": 14.05
      },
      {
        "height_cm": 85.93,
        "shoe_cm": 11.78
      },
      {
        "height_cm": 94.41,
        "shoe_cm": 13.51
      },
      {
        "height_cm": 113.57,
        "shoe_cm": 18.38
      },
      {
        "height_cm": 92.4,
        "shoe_cm": 12.52
      },
      {
        "height_cm": 122.57,
        "shoe_cm": 18.04
      },
      {
        "height_cm": 145.17,
        "shoe_cm": 22.23
      },
      {
        "height_cm": 80.52,
        "shoe_cm": 10.52
      },
      {
        "height_cm": 130.58,
        "shoe_cm": 20.35
      },
      {
        "height_cm": 91.08,
        "shoe_cm": 12.52
      },
      {
        "height_cm": 145.24,
        "shoe_cm": 24.21
      },
      {
        "height_cm": 116.52,
        "shoe_cm": 16.53
      },
      {
        "height_cm": 94.79,
        "shoe_cm": 13.43
      },
      {
        "height_cm": 96.44,
        "shoe_cm": 12.32
      },
      {
        "height_cm": 131.66,
        "shoe_cm": 20.58
      },
      {
        "height_cm": 79.73,
        "shoe_cm": 10.08
      },
      {
        "height_cm": 115.45,
        "shoe_cm": 17.54
      },
      {
        "height_cm": 99.33,
        "shoe_cm": 15.05
      },
      {
        "height_cm": 130.79,
        "shoe_cm": 18.7
      },
      {
        "height_cm": 81.58,
        "shoe_cm": 11.02
      },
      {
        "height_cm": 109.22,
        "shoe_cm": 14.03
      },
      {
        "height_cm": 113.22,
        "shoe_cm": 17.15
      },
      {
        "height_cm": 115.85,
        "shoe_cm": 17.81
      },
      {
        "height_cm": 112.98,
        "shoe_cm": 15.27
      },
      {
        "height_cm": 111.78,
        "shoe_cm": 16.91
      },
      {
        "height_cm": 103.9,
        "shoe_cm": 16.27
      },
      {
        "height_cm": 103.73,
        "shoe_cm": 14.2
      },
      {
        "height_cm": 83.02,
        "shoe_cm": 10.98
      },
      {
        "height_cm": 136.18,
        "shoe_cm": 17.32
      },
      {
        "height_cm": 80.88,
        "shoe_cm": 12.58
      },
      {
        "height_cm": 148.11,
        "shoe_cm": 21.51
      },
      {
        "height_cm": 114.84,
        "shoe_cm": 17.76
      },
      {
        "height_cm": 121.59,
        "shoe_cm": 17.88
      },
      {
        "height_cm": 124.87,
        "shoe_cm": 16.37
      },
      {
        "height_cm": 132.64,
        "shoe_cm": 17.34
      },
      {
        "height_cm": 108.4,
        "shoe_cm": 17.25
      },
      {
        "height_cm": 142.12,
        "shoe_cm": 21.31
      },
      {
        "height_cm": 152.17,
        "shoe_cm": 21.6
      },
      {
        "height_cm": 106.41,
        "shoe_cm": 15.82
      },
      {
        "height_cm": 90.9,
        "shoe_cm": 13.5
      },
      {
        "height_cm": 152.78,
        "shoe_cm": 21.64
      },
      {
        "height_cm": 146.6,
        "shoe_cm": 19.25
      },
      {
        "height_cm": 87.14,
        "shoe_cm": 11.09
      },
      {
        "height_cm": 97.49,
        "shoe_cm": 12.75
      },
      {
        "height_cm": 149.46,
        "shoe_cm": 22.26
      },
      {
        "height_cm": 149.29,
        "shoe_cm": 23.87
      },
      {
        "height_cm": 141.05,
        "shoe_cm": 20.34
      },
      {
        "height_cm": 105.48,
        "shoe_cm": 14.3
      },
      {
        "height_cm": 101.59,
        "shoe_cm": 16.6
      },
      {
        "height_cm": 147.2,
        "shoe_cm": 23.04
      },
      {
        "height_cm": 133.28,
        "shoe_cm": 17.2
      },
      {
        "height_cm": 120.57,
        "shoe_cm": 17.26
      },
      {
        "height_cm": 141.58,
        "shoe_cm": 18.33
      },
      {
        "height_cm": 121.72,
        "shoe_cm": 17.37
      },
      {
        "height_cm": 133.54,
        "shoe_cm": 19.57
      },
      {
        "height_cm": 100.57,
        "shoe_cm": 13.32
      },
      {
        "height_cm": 89.95,
        "shoe_cm": 12.54
      },
      {
        "height_cm": 136.96,
        "shoe_cm": 17.59
      },
      {
        "height_cm": 95.05,
        "shoe_cm": 14.4
      },
      {
        "height_cm": 125.55,
        "shoe_cm": 16.0
      },
      {
        "height_cm": 106.88,
        "shoe_cm": 13.74
      },
      {
        "height_cm": 96.34,
        "shoe_cm": 12.65
      },
      {
        "height_cm": 146.07,
        "shoe_cm": 22.07
      },
      {
        "height_cm": 126.85,
        "shoe_cm": 20.41
      },
      {
        "height_cm": 132.71,
        "shoe_cm": 17.38
      },
      {
        "height_cm": 141.82,
        "shoe_cm": 20.0
      },
      {
        "height_cm": 105.39,
        "shoe_cm": 16.75
      },
      {
        "height_cm": 109.98,
        "shoe_cm": 17.02
      },
      {
        "height_cm": 124.85,
        "shoe_cm": 20.75
      },
      {
        "height_cm": 140.53,
        "shoe_cm": 19.5
      },
      {
        "height_cm": 85.83,
        "shoe_cm": 12.7
      },
      {
        "height_cm": 102.56,
        "shoe_cm": 14.78
      },
      {
        "height_cm": 134.3,
        "shoe_cm": 21.89
      },
      {
        "height_cm": 152.31,
        "shoe_cm": 19.74
      },
      {
        "height_cm": 152.45,
        "shoe_cm": 19.17
      },
      {
        "height_cm": 139.15,
        "shoe_cm": 21.9
      },
      {
        "height_cm": 96.47,
        "shoe_cm": 12.16
      },
      {
        "height_cm": 133.16,
        "shoe_cm": 19.05
      },
      {
        "height_cm": 88.72,
        "shoe_cm": 11.73
      },
      {
        "height_cm": 99.21,
        "shoe_cm": 15.58
      },
      {
        "height_cm": 122.43,
        "shoe_cm": 17.22
      },
      {
        "height_cm": 147.62,
        "shoe_cm": 21.11
      },
      {
        "height_cm": 86.47,
        "shoe_cm": 13.46
      },
      {
        "height_cm": 123.65,
        "shoe_cm": 18.89
      },
      {
        "height_cm": 121.01,
        "shoe_cm": 15.91
      },
      {
        "height_cm": 130.27,
        "shoe_cm": 18.37
      },
      {
        "height_cm": 82.22,
        "shoe_cm": 10.43
      },
      {
        "height_cm": 118.15,
        "shoe_cm": 17.59
      },
      {
        "height_cm": 98.13,
        "shoe_cm": 15.09
      },
      {
        "height_cm": 80.63,
        "shoe_cm": 12.92
      },
      {
        "height_cm": 151.06,
        "shoe_cm": 24.11
      },
      {
        "height_cm": 135.76,
        "shoe_cm": 20.97
      },
      {
        "height_cm": 132.25,
        "shoe_cm": 18.98
      },
      {
        "height_cm": 149.34,
        "shoe_cm": 22.76
      },
      {
        "height_cm": 123.61,
        "shoe_cm": 19.3
      },
      {
        "height_cm": 148.12,
        "shoe_cm": 23.85
      },
      {
        "height_cm": 149.49,
        "shoe_cm": 19.65
      },
      {
        "height_cm": 102.54,
        "shoe_cm": 14.4
      },
      {
        "height_cm": 80.47,
        "shoe_cm": 11.09
      },
      {
        "height_cm": 145.05,
        "shoe_cm": 22.59
      },
      {
        "height_cm": 144.99,
        "shoe_cm": 19.87
      },
      {
        "height_cm": 120.94,
        "shoe_cm": 15.3
      },
      {
        "height_cm": 124.85,
        "shoe_cm": 17.69
      },
      {
        "height_cm": 90.01,
        "shoe_cm": 13.66
      },
      {
        "height_cm": 132.86,
        "shoe_cm": 18.39
      },
      {
        "height_cm": 107.87,
        "shoe_cm": 15.1
      },
      {
        "height_cm": 141.62,
        "shoe_cm": 18.58
      },
      {
        "height_cm": 101.39,
        "shoe_cm": 14.38
      },
      {
        "height_cm": 121.5,
        "shoe_cm": 17.21
      },
      {
        "height_cm": 151.78,
        "shoe_cm": 21.19
      },
      {
        "height_cm": 82.62,
        "shoe_cm": 11.0
      },
      {
        "height_cm": 114.73,
        "shoe_cm": 16.61
      },
      {
        "height_cm": 101.02,
        "shoe_cm": 13.31
      },
      {
        "height_cm": 81.35,
        "shoe_cm": 13.0
      },
      {
        "height_cm": 131.83,
        "shoe_cm": 17.51
      },
      {
        "height_cm": 143.93,
        "shoe_cm": 18.46
      },
      {
        "height_cm": 114.26,
        "shoe_cm": 16.44
      },
      {
        "height_cm": 151.68,
        "shoe_cm": 23.59
      },
      {
        "height_cm": 121.34,
        "shoe_cm": 16.48
      },
      {
        "height_cm": 135.26,
        "shoe_cm": 18.06
      },
      {
        "height_cm": 146.15,
        "shoe_cm": 19.2
      },
      {
        "height_cm": 129.54,
        "shoe_cm": 20.41
      },
      {
        "height_cm": 116.71,
        "shoe_cm": 16.7
      },
      {
        "height_cm": 144.13,
        "shoe_cm": 19.85
      }
    ],
    "male": [
      {
        "height_cm": 91.75,
        "shoe_cm": 13.65
      },
      {
        "height_cm": 133.07,
        "shoe_cm": 19.75
      },
      {
        "height_cm": 149.13,
        "shoe_cm": 19.82
      },
      {
        "height_cm": 96.86,
        "shoe_cm": 13.05
      },
      {
        "height_cm": 78.11,
        "shoe_cm": 10.26
      },
      {
        "height_cm": 149.54,
        "shoe_cm": 19.65
      },
      {
        "height_cm": 142.85,
        "shoe_cm": 20.27
      },
      {
        "height_cm": 86.2,
        "shoe_cm": 11.01
      },
      {
        "height_cm": 88.24,
        "shoe_cm": 13.04
      },
      {
        "height_cm": 128.53,
        "shoe_cm": 20.98
      },
      {
        "height_cm": 148.45,
        "shoe_cm": 22.24
      },
      {
        "height_cm": 75.73,
        "shoe_cm": 11.36
      },
      {
        "height_cm": 138.98,
        "shoe_cm": 17.69
      },
      {
        "height_cm": 108.8,
        "shoe_cm": 14.9
      },
      {
        "height_cm": 109.71,
        "shoe_cm": 16.66
      },
      {
        "height_cm": 79.49,
        "shoe_cm": 12.25
      },
      {
        "height_cm": 106.26,
        "shoe_cm": 15.92
      },
      {
        "height_cm": 148.15,
        "shoe_cm": 20.83
      },
      {
        "height_cm": 81.87,
        "shoe_cm": 13.46
      },
      {
        "height_cm": 111.0,
        "shoe_cm": 17.95
      },
      {
        "height_cm": 108.95,
        "shoe_cm": 15.72
      },
      {
        "height_cm": 105.74,
        "shoe_cm": 14.7
      },
      {
        "height_cm": 111.28,
        "shoe_cm": 15.78
      },
      {
        "height_cm": 76.79,
        "shoe_cm": 12.33
      },
      {
        "height_cm": 108.55,
        "shoe_cm": 14.64
      },
      {
        "height_cm": 108.31,
        "shoe_cm": 15.01
      },
      {
        "height_cm": 124.59,
        "shoe_cm": 20.09
      },
      {
        "height_cm": 102.64,
        "shoe_cm": 14.1
      },
      {
        "height_cm": 119.04,
        "shoe_cm": 18.92
      },
      {
        "height_cm": 96.77,
        "shoe_cm": 13.37
      },
      {
        "height_cm": 79.49,
        "shoe_cm": 13.18
      },
      {
        "height_cm": 120.61,
        "shoe_cm": 19.29
      },
      {
        "height_cm": 131.48,
        "shoe_cm": 18.76
      },
      {
        "height_cm": 81.09,
        "shoe_cm": 12.04
      },
      {
        "height_cm": 97.42,
        "shoe_cm": 15.95
      },
      {
        "height_cm": 122.27,
        "shoe_cm": 18.68
      },
      {
        "height_cm": 145.93,
        "shoe_cm": 22.31
      },
      {
        "height_cm": 89.28,
        "shoe_cm": 11.43
      },
      {
        "height_cm": 92.16,
        "shoe_cm": 12.81
      },
      {
        "height_cm": 132.1,
        "shoe_cm": 17.7
      },
      {
        "height_cm": 121.62,
        "shoe_cm": 18.4
      },
      {
        "height_cm": 147.34,
        "shoe_cm": 19.86
      },
      {
        "height_cm": 122.33,
        "shoe_cm": 19.71
      },
      {
        "height_cm": 132.15,
        "shoe_cm": 21.94
      },
      {
        "height_cm": 139.34,
        "shoe_cm": 18.84
      },
      {
        "height_cm": 94.56,
        "shoe_cm": 14.04
      },
      {
        "height_cm": 140.89,
        "shoe_cm": 20.55
      },
      {
        "height_cm": 127.97,
        "shoe_cm": 17.69
      },
      {
        "height_cm": 106.21,
        "shoe_cm": 13.62
      },
      {
        "height_cm": 95.7,
        "shoe_cm": 13.47
      },
      {
        "height_cm": 105.09,
        "shoe_cm": 15.14
      },
      {
        "height_cm": 80.64,
        "shoe_cm": 11.54
      },
      {
        "height_cm": 114.54,
        "shoe_cm": 15.17
      },
      {
        "height_cm": 137.71,
        "shoe_cm": 19.35
      },
      {
        "height_cm": 147.51,
        "shoe_cm": 19.27
      },
      {
        "height_cm": 90.23,
        "shoe_cm": 11.45
      },
      {
        "height_cm": 112.62,
        "shoe_cm": 17.12
      },
      {
        "height_cm": 79.96,
        "shoe_cm": 10.55
      },
      {
        "height_cm": 117.87,
        "shoe_cm": 17.96
      },
      {
        "height_cm": 126.59,
        "shoe_cm": 16.54
      },
      {
        "height_cm": 91.24,
        "shoe_cm": 14.11
      },
      {
        "height_cm": 84.51,
        "shoe_cm": 12.8
      },
      {
        "height_cm": 95.38,
        "shoe_cm": 12.35
      },
      {
        "height_cm": 121.17,
        "shoe_cm": 16.23
      },
      {
        "height_cm": 75.48,
        "shoe_cm": 11.49
      },
      {
        "height_cm": 92.97,
        "shoe_cm": 14.56
      },
      {
        "height_cm": 141.5,
        "shoe_cm": 18.91
      },
      {
        "height_cm": 111.85,
        "shoe_cm": 14.76
      },
      {
        "height_cm": 83.53,
        "shoe_cm": 10.53
      },
      {
        "height_cm": 138.66,
        "shoe_cm": 17.93
      },
      {
        "height_cm": 149.61,
        "shoe_cm": 23.33
      },
      {
        "height_cm": 98.74,
        "shoe_cm": 13.73
      },
      {
        "height_cm": 120.98,
        "shoe_cm": 16.4
      },
      {
        "height_cm": 111.44,
        "shoe_cm": 18.13
      },
      {
        "height_cm": 96.98,
        "shoe_cm": 13.43
      },
      {
        "height_cm": 105.05,
        "shoe_cm": 17.11
      },
      {
        "height_cm": 110.16,
        "shoe_cm": 15.28
      },
      {
        "height_cm": 125.47,
        "shoe_cm": 18.9
      },
      {
        "height_cm": 133.44,
        "shoe_cm": 21.88
      },
      {
        "height_cm": 80.92,
        "shoe_cm": 11.45
      },
      {
        "height_cm": 116.58,
        "shoe_cm": 16.02
      },
      {
        "height_cm": 121.47,
        "shoe_cm": 15.88
      },
      {
        "height_cm": 75.88,
        "shoe_cm": 12.53
      },
      {
        "height_cm": 136.85,
        "shoe_cm": 20.57
      },
      {
        "height_cm": 106.79,
        "shoe_cm": 13.54
      },
      {
        "height_cm": 142.17,
        "shoe_cm": 21.92
      },
      {
        "height_cm": 147.1,
        "shoe_cm": 19.8
      },
      {
        "height_cm": 131.12,
        "shoe_cm": 20.57
      },
      {
        "height_cm": 147.76,
        "shoe_cm": 23.48
      },
      {
        "height_cm": 118.93,
        "shoe_cm": 18.13
      },
      {
        "height_cm": 111.05,
        "shoe_cm": 16.42
      },
      {
        "height_cm": 76.69,
        "shoe_cm": 9.74
      },
      {
        "height_cm": 109.22,
        "shoe_cm": 14.8
      },
      {
        "height_cm": 90.8,
        "shoe_cm": 11.72
      },
      {
        "height_cm": 116.3,
        "shoe_cm": 15.58
      },
      {
        "height_cm": 102.84,
        "shoe_cm": 15.87
      },
      {
        "height_cm": 141.71,
        "shoe_cm": 18.66
      },
      {
        "height_cm": 91.47,
        "shoe_cm": 14.78
      },
      {
        "height_cm": 106.03,
        "shoe_cm": 15.78
      },
      {
        "height_cm": 103.45,
        "shoe_cm": 13.2
      },
      {
        "height_cm": 98.99,
        "shoe_cm": 16.18
      },
      {
        "height_cm": 135.74,
        "shoe_cm": 21.67
      },
      {
        "height_cm": 133.37,
        "shoe_cm": 22.11
      },
      {
        "height_cm": 108.02,
        "shoe_cm": 13.91
      },
      {
        "height_cm": 111.8,
        "shoe_cm": 17.32
      },
      {
        "height_cm": 110.62,
        "shoe_cm": 14.68
      },
      {
        "height_cm": 82.06,
        "shoe_cm": 11.19
      },
      {
        "height_cm": 128.6,
        "shoe_cm": 19.57
      },
      {
        "height_cm": 84.12,
        "shoe_cm": 13.0
      },
      {
        "height_cm": 105.82,
        "shoe_cm": 14.13
      },
      {
        "height_cm": 87.63,
        "shoe_cm": 11.04
      },
      {
        "height_cm": 84.36,
        "shoe_cm": 10.88
      },
      {
        "height_cm": 112.85,
        "shoe_cm": 16.55
      },
      {
        "height_cm": 107.02,
        "shoe_cm": 14.83
      },
      {
        "height_cm": 104.91,
        "shoe_cm": 14.57
      },
      {
        "height_cm": 89.71,
        "shoe_cm": 14.76
      },
      {
        "height_cm": 106.53,
        "shoe_cm": 14.46
      },
      {
        "height_cm": 93.92,
        "shoe_cm": 12.32
      },
      {
        "height_cm": 95.7,
        "shoe_cm": 14.25
      },
      {
        "height_cm": 90.7,
        "shoe_cm": 11.75
      },
      {
        "height_cm": 86.37,
        "shoe_cm": 10.82
      },
      {
        "height_cm": 83.88,
        "shoe_cm": 11.71
      },
      {
        "height_cm": 83.45,
        "shoe_cm": 10.68
      },
      {
        "height_cm": 79.32,
        "shoe_cm": 11.55
      },
      {
        "height_cm": 107.21,
        "shoe_cm": 16.16
      },
      {
        "height_cm": 122.39,
        "shoe_cm": 20.12
      },
      {
        "height_cm": 95.91,
        "shoe_cm": 13.21
      },
      {
        "height_cm": 85.8,
        "shoe_cm": 13.13
      },
      {
        "height_cm": 129.44,
        "shoe_cm": 16.29
      },
      {
        "height_cm": 110.45,
        "shoe_cm": 15.13
      },
      {
        "height_cm": 132.78,
        "shoe_cm": 17.81
      },
      {
        "height_cm": 129.82,
        "shoe_cm": 16.52
      },
      {
        "height_cm": 102.62,
        "shoe_cm": 13.52
      },
      {
        "height_cm": 129.68,
        "shoe_cm": 16.28
      },
      {
        "height_cm": 125.24,
        "shoe_cm": 17.33
      },
      {
        "height_cm": 103.44,
        "shoe_cm": 16.23
      },
      {
        "height_cm": 142.13,
        "shoe_cm": 22.14
      },
      {
        "height_cm": 86.46,
        "shoe_cm": 11.12
      },
      {
        "height_cm": 77.78,
        "shoe_cm": 12.21
      },
      {
        "height_cm": 83.71,
        "shoe_cm": 10.87
      },
      {
        "height_cm": 83.43,
        "shoe_cm": 10.83
      },
      {
        "height_cm": 95.67,
        "shoe_cm": 14.8
      },
      {
        "height_cm": 147.66,
        "shoe_cm": 19.69
      },
      {
        "height_cm": 100.18,
        "shoe_cm": 13.73
      },
      {
        "height_cm": 126.0,
        "shoe_cm": 18.68
      },
      {
        "height_cm": 128.02,
        "shoe_cm": 17.08
      },
      {
        "height_cm": 87.52,
        "shoe_cm": 12.6
      },
      {
        "height_cm": 98.49,
        "shoe_cm": 15.85
      },
      {
        "height_cm": 140.8,
        "shoe_cm": 18.16
      },
      {
        "height_cm": 93.19,
        "shoe_cm": 13.93
      },
      {
        "height_cm": 144.77,
        "shoe_cm": 19.08
      },
      {
        "height_cm": 93.01,
        "shoe_cm": 11.84
      },
      {
        "height_cm": 121.42,
        "shoe_cm": 15.29
      },
      {
        "height_cm": 93.69,
        "shoe_cm": 13.71
      },
      {
        "height_cm": 127.33,
        "shoe_cm": 17.21
      },
      {
        "height_cm": 119.03,
        "shoe_cm": 19.57
      },
      {
        "height_cm": 88.11,
        "shoe_cm": 11.34
      },
      {
        "height_cm": 136.32,
        "shoe_cm": 17.76
      },
      {
        "height_cm": 119.72,
        "shoe_cm": 17.33
      },
      {
        "height_cm": 92.37,
        "shoe_cm": 13.75
      },
      {
        "height_cm": 82.91,
        "shoe_cm": 10.81
      },
      {
        "height_cm": 130.56,
        "shoe_cm": 16.36
      },
      {
        "height_cm": 121.57,
        "shoe_cm": 15.4
      },
      {
        "height_cm": 118.84,
        "shoe_cm": 16.7
      },
      {
        "height_cm": 139.95,
        "shoe_cm": 21.53
      },
      {
        "height_cm": 141.26,
        "shoe_cm": 21.0
      },
      {
        "height_cm": 138.41,
        "shoe_cm": 22.3
      },
      {
        "height_cm": 111.44,
        "shoe_cm": 15.3
      },
      {
        "height_cm": 141.61,
        "shoe_cm": 19.2
      },
      {
        "height_cm": 149.61,
        "shoe_cm": 24.4
      },
      {
        "height_cm": 146.27,
        "shoe_cm": 22.41
      },
      {
        "height_cm": 97.06,
        "shoe_cm": 12.22
      },
      {
        "height_cm": 84.42,
        "shoe_cm": 11.71
      },
      {
        "height_cm": 115.87,
        "shoe_cm": 15.69
      },
      {
        "height_cm": 119.86,
        "shoe_cm": 15.43
      },
      {
        "height_cm": 148.5,
        "shoe_cm": 22.27
      },
      {
        "height_cm": 140.45,
        "shoe_cm": 19.79
      },
      {
        "height_cm": 95.39,
        "shoe_cm": 14.88
      },
      {
        "height_cm": 126.88,
        "shoe_cm": 16.5
      },
      {
        "height_cm": 121.5,
        "shoe_cm": 19.5
      },
      {
        "height_cm": 87.12,
        "shoe_cm": 14.46
      },
      {
        "height_cm": 134.74,
        "shoe_cm": 18.32
      },
      {
        "height_cm": 120.13,
        "shoe_cm": 17.34
      },
      {
        "height_cm": 149.96,
        "shoe_cm": 19.6
      },
      {
        "height_cm": 99.35,
        "shoe_cm": 13.39
      },
      {
        "height_cm": 102.27,
        "shoe_cm": 14.12
      },
      {
        "height_cm": 80.83,
        "shoe_cm": 10.83
      },
      {
        "height_cm": 148.94,
        "shoe_cm": 18.76
      },
      {
        "height_cm": 88.62,
        "shoe_cm": 13.35
      },
      {
        "height_cm": 87.49,
        "shoe_cm": 11.35
      },
      {
        "height_cm": 125.36,
        "shoe_cm": 20.19
      },
      {
        "height_cm": 82.03,
        "shoe_cm": 10.47
      },
      {
        "height_cm": 127.55,
        "shoe_cm": 18.18
      },
      {
        "height_cm": 109.31,
        "shoe_cm": 15.46
      },
      {
        "height_cm": 140.01,
        "shoe_cm": 18.93
      },
      {
        "height_cm": 103.57,
        "shoe_cm": 14.6
      },
      {
        "height_cm": 132.06,
        "shoe_cm": 21.03
      },
      {
        "height_cm": 103.64,
        "shoe_cm": 14.68
      },
      {
        "height_cm": 138.11,
        "shoe_cm": 17.97
      }
    ]
  },
  "ageFoot": [
    {
      "age": 6,
      "girl_cm": 18.55,
      "boy_cm": 18.27,
      "girl_minus_boy_cm": 0.28
    },
    {
      "age": 7,
      "girl_cm": 20.24,
      "boy_cm": 19.76,
      "girl_minus_boy_cm": 0.48
    },
    {
      "age": 8,
      "girl_cm": 21.01,
      "boy_cm": 20.61,
      "girl_minus_boy_cm": 0.4
    },
    {
      "age": 9,
      "girl_cm": 20.34,
      "boy_cm": 20.01,
      "girl_minus_boy_cm": 0.33
    },
    {
      "age": 10,
      "girl_cm": 20.83,
      "boy_cm": 20.75,
      "girl_minus_boy_cm": 0.08
    },
    {
      "age": 11,
      "girl_cm": 21.29,
      "boy_cm": 21.32,
      "girl_minus_boy_cm": -0.03
    },
    {
      "age": 12,
      "girl_cm": 21.83,
      "boy_cm": 21.98,
      "girl_minus_boy_cm": -0.15
    },
    {
      "age": 13,
      "girl_cm": 22.36,
      "boy_cm": 22.69,
      "girl_minus_boy_cm": -0.33
    },
    {
      "age": 14,
      "girl_cm": 22.66,
      "boy_cm": 23.16,
      "girl_minus_boy_cm": -0.5
    }
  ],
  "bmiShape": [
    {
      "bmi": 12,
      "girl": 22.97,
      "boy": 25.28
    },
    {
      "bmi": 13,
      "girl": 23.38,
      "boy": 22.97
    },
    {
      "bmi": 14,
      "girl": 26.51,
      "boy": 28.47
    },
    {
      "bmi": 15,
      "girl": 24.47,
      "boy": 26.9
    },
    {
      "bmi": 16,
      "girl": 25.96,
      "boy": 28.03
    },
    {
      "bmi": 17,
      "girl": 26.22,
      "boy": 26.07
    },
    {
      "bmi": 18,
      "girl": 26.66,
      "boy": 26.76
    },
    {
      "bmi": 19,
      "girl": 26.92,
      "boy": 30.18
    },
    {
      "bmi": 20,
      "girl": 27.82,
      "boy": 26.63
    },
    {
      "bmi": 21,
      "girl": 26.35,
      "boy": 30.38
    },
    {
      "bmi": 22,
      "girl": 27.51,
      "boy": 30.13
    },
    {
      "bmi": 23,
      "girl": 29.86,
      "boy": 28.07
    },
    {
      "bmi": 24,
      "girl": 28.67,
      "boy": 30.19
    }
  ],
  "symmetry": [
    {
      "age": 2,
      "left_10_20": 36,
      "left_over_20": 17,
      "right_over_20": 11,
      "right_10_20": 27,
      "same": 154,
      "total": 245,
      "same_pct": 62.857142857142854
    },
    {
      "age": 3,
      "left_10_20": 27,
      "left_over_20": 13,
      "right_over_20": 8,
      "right_10_20": 20,
      "same": 131,
      "total": 199,
      "same_pct": 65.82914572864321
    },
    {
      "age": 4,
      "left_10_20": 22,
      "left_over_20": 10,
      "right_over_20": 7,
      "right_10_20": 16,
      "same": 118,
      "total": 173,
      "same_pct": 68.20809248554913
    },
    {
      "age": 5,
      "left_10_20": 18,
      "left_over_20": 9,
      "right_over_20": 5,
      "right_10_20": 13,
      "same": 108,
      "total": 153,
      "same_pct": 70.58823529411765
    },
    {
      "age": 6,
      "left_10_20": 15,
      "left_over_20": 7,
      "right_over_20": 5,
      "right_10_20": 11,
      "same": 101,
      "total": 139,
      "same_pct": 72.66187050359713
    },
    {
      "age": 7,
      "left_10_20": 13,
      "left_over_20": 6,
      "right_over_20": 4,
      "right_10_20": 9,
      "same": 95,
      "total": 127,
      "same_pct": 74.80314960629921
    },
    {
      "age": 8,
      "left_10_20": 11,
      "left_over_20": 5,
      "right_over_20": 3,
      "right_10_20": 8,
      "same": 90,
      "total": 117,
      "same_pct": 76.92307692307692
    },
    {
      "age": 9,
      "left_10_20": 9,
      "left_over_20": 5,
      "right_over_20": 3,
      "right_10_20": 6,
      "same": 86,
      "total": 109,
      "same_pct": 78.89908256880734
    },
    {
      "age": 10,
      "left_10_20": 7,
      "left_over_20": 4,
      "right_over_20": 2,
      "right_10_20": 5,
      "same": 81,
      "total": 99,
      "same_pct": 81.81818181818181
    },
    {
      "age": 11,
      "left_10_20": 6,
      "left_over_20": 3,
      "right_over_20": 2,
      "right_10_20": 4,
      "same": 78,
      "total": 93,
      "same_pct": 83.87096774193549
    },
    {
      "age": 12,
      "left_10_20": 5,
      "left_over_20": 3,
      "right_over_20": 1,
      "right_10_20": 3,
      "same": 75,
      "total": 87,
      "same_pct": 86.20689655172414
    },
    {
      "age": 13,
      "left_10_20": 4,
      "left_over_20": 2,
      "right_over_20": 1,
      "right_10_20": 2,
      "same": 72,
      "total": 81,
      "same_pct": 88.88888888888889
    },
    {
      "age": 14,
      "left_10_20": 3,
      "left_over_20": 2,
      "right_over_20": 1,
      "right_10_20": 1,
      "same": 70,
      "total": 77,
      "same_pct": 90.9090909090909
    }
  ],
  "radar": {
    "axes": [
      "身高",
      "兜跟围长",
      "跗骨围长",
      "跖趾围长",
      "鞋码",
      "脚长",
      "体重"
    ],
    "rows": [
      {
        "age": 9,
        "scores": [
          43,
          29,
          37,
          37,
          38,
          31,
          41
        ]
      },
      {
        "age": 10,
        "scores": [
          53,
          32,
          42,
          46,
          43,
          42,
          49
        ]
      },
      {
        "age": 11,
        "scores": [
          66,
          37,
          47,
          60,
          57,
          59,
          65
        ]
      },
      {
        "age": 12,
        "scores": [
          84,
          45,
          55,
          70,
          71,
          71,
          79
        ]
      }
    ]
  },
  "leftovers": {
    "pressure": {
      "mounted": false,
      "source": "draw1.js",
      "sites": [
        "位点1",
        "位点2",
        "位点3",
        "位点4",
        "位点5",
        "位点6",
        "位点7"
      ],
      "normal_pa_label": [
        90,
        50,
        39,
        50,
        120,
        82,
        80
      ],
      "diabetic_foot_pa_label": [
        290,
        200,
        20,
        132,
        15,
        200,
        90
      ],
      "disclaimer": "Unmounted sketch. Not a clinical plantar-pressure study."
    },
    "thickness": {
      "mounted": false,
      "source": "draw2.js",
      "sites": [
        "位点1",
        "位点2",
        "位点3",
        "位点4",
        "位点5",
        "位点6",
        "位点7",
        "位点8",
        "位点9",
        "位点10",
        "位点11",
        "位点12",
        "位点13",
        "位点14"
      ],
      "normal_mm": [
        11.6,
        12.3,
        12.1,
        13.7,
        12.6,
        10.4,
        12.2,
        11.6,
        13.2,
        12.9,
        11.4,
        13.4,
        10.2,
        11.5
      ],
      "diabetic_foot_mm": [
        13.2,
        13.6,
        12.9,
        14.6,
        14.9,
        13,
        15.7,
        16.1,
        14.2,
        15.8,
        15.9,
        13.7,
        12.9,
        14.9
      ],
      "claimed_diff_um": [
        16,
        13,
        8,
        9,
        23,
        26,
        35,
        45,
        10,
        29,
        45,
        3,
        27,
        34
      ],
      "computed_diff_mm": [
        1.6,
        1.3,
        0.8,
        0.9,
        2.3,
        2.6,
        3.5,
        4.5,
        1.0,
        2.9,
        4.5,
        0.3,
        2.7,
        3.4
      ],
      "computed_diff_um": [
        1600.0,
        1300.0,
        800.0,
        900.0,
        2300.0,
        2600.0,
        3500.0,
        4500.0,
        1000.0,
        2900.0,
        4500.0,
        300.0,
        2700.0,
        3400.0
      ],
      "claimed_um_mismatch_count": 14,
      "disclaimer": "Every claimed 差值:um disagrees with (diabetic-normal)*1000."
    }
  },
  "stats": {
    "female": {
      "label": "female",
      "n": 199,
      "height_cm": {
        "min": 79.73,
        "max": 152.78,
        "mean": 116.85517587939698,
        "sd": 21.39634493576705
      },
      "shoe_cm": {
        "min": 10.08,
        "max": 24.21,
        "mean": 16.76145728643216,
        "sd": 3.2996784947356437
      },
      "pearson_r": 0.913516196367574,
      "ols_shoe_from_height": {
        "slope": 0.1408796575674912,
        "intercept": 0.29894012355375565,
        "r_squared": 0.83451184102588,
        "residual_sd": 1.345719577718482
      }
    },
    "male": {
      "label": "male",
      "n": 199,
      "height_cm": {
        "min": 75.48,
        "max": 149.96,
        "mean": 111.81859296482413,
        "sd": 21.754246259833632
      },
      "shoe_cm": {
        "min": 9.74,
        "max": 24.4,
        "mean": 15.963417085427135,
        "sd": 3.4056937444104856
      },
      "pearson_r": 0.9156199722751241,
      "ols_shoe_from_height": {
        "slope": 0.14334310527652086,
        "intercept": -0.06500725780208683,
        "r_squared": 0.8383599336290991,
        "residual_sd": 1.3727124852053776
      }
    },
    "pooled": {
      "label": "pooled",
      "n": 398,
      "height_cm": {
        "min": 75.48,
        "max": 152.78,
        "mean": 114.33688442211056,
        "sd": 21.69586507962655
      },
      "shoe_cm": {
        "min": 9.74,
        "max": 24.4,
        "mean": 16.362437185929647,
        "sd": 3.3726267842018163
      },
      "pearson_r": 0.9157414510413382,
      "ols_shoe_from_height": {
        "slope": 0.14235220093095338,
        "intercept": 0.08633004085417184,
        "r_squared": 0.8385824051552955,
        "residual_sd": 1.3567236048137794
      }
    },
    "age_crossover": {
      "first_age_boys_longer": 11,
      "series": [
        {
          "age": 6,
          "girl_cm": 18.55,
          "boy_cm": 18.27,
          "girl_minus_boy_cm": 0.28
        },
        {
          "age": 7,
          "girl_cm": 20.24,
          "boy_cm": 19.76,
          "girl_minus_boy_cm": 0.48
        },
        {
          "age": 8,
          "girl_cm": 21.01,
          "boy_cm": 20.61,
          "girl_minus_boy_cm": 0.4
        },
        {
          "age": 9,
          "girl_cm": 20.34,
          "boy_cm": 20.01,
          "girl_minus_boy_cm": 0.33
        },
        {
          "age": 10,
          "girl_cm": 20.83,
          "boy_cm": 20.75,
          "girl_minus_boy_cm": 0.08
        },
        {
          "age": 11,
          "girl_cm": 21.29,
          "boy_cm": 21.32,
          "girl_minus_boy_cm": -0.03
        },
        {
          "age": 12,
          "girl_cm": 21.83,
          "boy_cm": 21.98,
          "girl_minus_boy_cm": -0.15
        },
        {
          "age": 13,
          "girl_cm": 22.36,
          "boy_cm": 22.69,
          "girl_minus_boy_cm": -0.33
        },
        {
          "age": 14,
          "girl_cm": 22.66,
          "boy_cm": 23.16,
          "girl_minus_boy_cm": -0.5
        }
      ]
    },
    "rings": {
      "thin": {
        "highlighted": 50,
        "placeholder": 180,
        "percent": 21.73913043478261
      },
      "thick": {
        "highlighted": 435,
        "placeholder": 2400,
        "percent": 15.343915343915343
      }
    },
    "symmetry_age_14": {
      "age": 14,
      "left_10_20": 3,
      "left_over_20": 2,
      "right_over_20": 1,
      "right_10_20": 1,
      "same": 70,
      "total": 77,
      "same_pct": 90.9090909090909
    },
    "leftover_thickness_mismatches": 14
  },
  "workbookAnswers": {
    "crossover_age": 11,
    "pooled_r_3dp": 0.916,
    "female_n": 199,
    "male_n": 199,
    "thin_ring_pct_1dp": 21.7,
    "thick_ring_pct_1dp": 15.3,
    "symmetry_same_pct_age_14_1dp": 90.9,
    "thickness_mismatch_count": 14,
    "radar_age_12_height_score": 84,
    "ols_pooled_slope_4dp": 0.1424
  }
};
