#!/usr/bin/env node
/**
 * Re-extract dashboard / draw*.js series into examples/data/*.json.
 * Run from the repository root: node examples/scripts/extract-data.js
 */
"use strict";

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "../..");
const outDir = path.join(root, "examples/data");
const src = fs.readFileSync(path.join(root, "js/index.js"), "utf8");

function extractFirstArrayAfter(marker) {
  const i = src.indexOf(marker);
  if (i < 0) {
    throw new Error("marker not found: " + marker);
  }
  const start = src.indexOf("[[", i);
  if (start < 0) {
    throw new Error("no nested array after " + marker);
  }
  let depth = 0;
  let end = start;
  for (let j = start; j < src.length; j++) {
    if (src[j] === "[") depth++;
    else if (src[j] === "]") {
      depth--;
      if (depth === 0) {
        end = j + 1;
        break;
      }
    }
  }
  return JSON.parse(src.slice(start, end));
}

function stats(points) {
  const xs = points.map((p) => p[0]);
  const ys = points.map((p) => p[1]);
  const mean = (a) => a.reduce((s, v) => s + v, 0) / a.length;
  const min = (a) => Math.min.apply(null, a);
  const max = (a) => Math.max.apply(null, a);
  return {
    n: points.length,
    heightCm: { min: min(xs), max: max(xs), mean: +mean(xs).toFixed(2) },
    shoeSizeCm: { min: min(ys), max: max(ys), mean: +mean(ys).toFixed(2) },
  };
}

function write(name, obj) {
  const file = path.join(outDir, name);
  fs.writeFileSync(file, JSON.stringify(obj, null, 2) + "\n");
  process.stdout.write("wrote " + path.relative(root, file) + "\n");
}

fs.mkdirSync(outDir, { recursive: true });

const female = extractFirstArrayAfter("name: '女性'");
const male = extractFirstArrayAfter("name: '男性'");

write("height-shoe-size.json", {
  description:
    "Height (cm) vs shoe size / foot length (cm) scatter for girls and boys.",
  units: { x: "height_cm", y: "shoe_size_cm" },
  female: { seriesName: "女性", points: female, summary: stats(female) },
  male: { seriesName: "男性", points: male, summary: stats(male) },
});

write("age-foot-length.json", {
  description:
    "Mean foot length (cm) by age 6-14, plus girl-minus-boy difference.",
  ages: [6, 7, 8, 9, 10, 11, 12, 13, 14],
  femaleFootLengthCm: [18.55, 20.24, 21.01, 20.34, 20.83, 21.29, 21.83, 22.36, 22.66],
  maleFootLengthCm: [18.27, 19.76, 20.61, 20.01, 20.75, 21.32, 21.98, 22.69, 23.16],
  femaleMinusMaleCm: [0.28, 0.48, 0.4, 0.33, 0.08, -0.03, -0.15, -0.33, -0.5],
});

write("bmi-plumpness.json", {
  description:
    "Foot plumpness (dashboard label: 脚长/脚宽) vs BMI integer bins 12-24, plus ring-chart placeholders for thin/wide feet.",
  note: "Y values sit in the 22-30 range, so they are not raw length/width ratios. Treat them as the dashboard plumpness index as plotted.",
  bmi: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
  femalePlumpness: [22.97, 23.38, 26.51, 24.47, 25.96, 26.22, 26.66, 26.92, 27.82, 26.35, 27.51, 29.86, 28.67],
  malePlumpness: [25.28, 22.97, 28.47, 26.9, 28.03, 26.07, 26.76, 30.18, 26.63, 30.38, 30.13, 28.07, 30.19],
  thinFootRing: { value: 50, placeholder: 180, label: "过瘦脚占比" },
  wideFootRing: { value: 435, placeholder: 2400, label: "过胖脚占比" },
});

write("growth-radar.json", {
  description: "Normalized 0-100 radar scores for ages 9-12 across seven growth axes.",
  axes: ["身高", "兜跟围长", "跗骨围长", "跖趾围长", "鞋码", "脚长", "体重"],
  series: [
    { age: 9, values: [43, 29, 37, 37, 38, 31, 41] },
    { age: 10, values: [53, 32, 42, 46, 43, 42, 49] },
    { age: 11, values: [66, 37, 47, 60, 57, 59, 65] },
    { age: 12, values: [84, 45, 55, 70, 71, 71, 79] },
  ],
  note: "Age 12 shoe-size and foot-length scores are 77-6 and 79-8 in js/index.js (71 and 71).",
});

const time = ["2岁", "3岁", "4岁", "5岁", "6岁", "7岁", "8岁", "9岁", "10岁", "11岁", "12岁", "13岁", "14岁"];
const pie = time.map(function (t, i) {
  const a = Math.round(36 - 13 * Math.log(i + 1));
  const b = Math.round(17 - 6 * Math.log(i + 1));
  const c = Math.round(11 - 4 * Math.log(i + 1));
  const d = Math.round(27 - 10 * Math.log(i + 1));
  return {
    age: t,
    same: 63 + a + b + c + d,
    left10to20: a,
    leftOver20: b,
    rightOver20: c,
    right10to20: d,
  };
});

write("bilateral-ratio.json", {
  description:
    "Left/right foot size categories by age. Values are generated by the same log-decay formula as js/index.js, not raw survey counts.",
  formula: {
    a: "round(36 - 13 * ln(ageIndex+1))  // left 10-20% larger",
    b: "round(17 - 6 * ln(ageIndex+1))   // left >20% larger",
    c: "round(11 - 4 * ln(ageIndex+1))   // right >20% larger",
    d: "round(27 - 10 * ln(ageIndex+1))  // right 10-20% larger",
    same: "63 + a + b + c + d",
  },
  ages: pie,
});

write("plantar-pressure.json", {
  description:
    "Plantar pressure (Pa) at seven sites for typical vs diabetic-foot adult groups. From draw1.js.",
  sites: ["位点一", "位点二", "位点三", "位点四", "位点五", "位点六", "位点七"],
  typicalPa: [90, 50, 39, 50, 120, 82, 80],
  diabeticFootPa: [290, 200, 20, 132, 15, 200, 90],
  sourceRing: { typicalShare: 335, placeholder: 180 },
});

write("tissue-thickness.json", {
  description:
    "Subcutaneous tissue thickness (mm) at 14 plantar sites, plus difference series labeled um in draw2.js.",
  sites: Array.from({ length: 14 }, function (_, i) {
    return "位点" + (i + 1);
  }),
  typicalAdultMm: [11.6, 12.3, 12.1, 13.7, 12.6, 10.4, 12.2, 11.6, 13.2, 12.9, 11.4, 13.4, 10.2, 11.5],
  diabeticFootAdultMm: [13.2, 13.6, 12.9, 14.6, 14.9, 13, 15.7, 16.1, 14.2, 15.8, 15.9, 13.7, 12.9, 14.9],
  differenceUm: [16, 13, 8, 9, 23, 26, 35, 45, 10, 29, 45, 3, 27, 34],
});
